### PR TITLE
Provide Docker support.

### PR DESCRIPTION
**Pull request by bemosior**
I believe these changes comprise everything necessary to Dockerize Atlas2 (#35).

[Docker Compose](https://docs.docker.com/compose/) is a tool for managing multi-container application stacks easily. This stack involves two containers. One is the Atlas2 code (see the `Dockerfile`). The other is a MongoDB instance.

Give it a try!

`docker-compose up` will build the Docker image and spin up the full stack locally. Visit http://localhost:6001 to test it out.

`docker-compose run web npm test` will spin up the full stack and run the test suite.

There is one test failure that only occurs inside the container that I do not yet understand. I suspect you might be able to shed some light on it before I begin troubleshooting:
```
127.0.0.1 - - [29/Jun/2017:05:44:09 +0000] "GET /img/595493a89a646500169af277.png HTTP/1.1" 200 - "-" "node-superagent/3.5.2"
[2017-06-29 05:44:09.275] [INFO] console -     1) download a png
[2017-06-29 05:44:09.276] [INFO] console -
[2017-06-29 05:44:09.276] [INFO] console -
[2017-06-29 05:44:09.276] [INFO] console -   17 passing (17s)
[2017-06-29 05:44:09.277] [INFO] console -   1 failing
[2017-06-29 05:44:09.277] [INFO] console -
[2017-06-29 05:44:09.277] [INFO] console -   1) Workspaces & maps download a png:
     AssertionError: expected 12812 to be within 15000..16000
```

Let me know what questions and concerns you have. I'm happy to make improvements as I find time..

### CODE REVIEW

**Comment by cdaniel** [comment]
The failing test is a simple verification of the server side png generation. In this case, the file is slightly smaller than expected (12812 vs expected 15000 bytes). Depending on a platform, the file is typically around 15100. It may mean that either server side rendering is broken (possibly due to missing dependency) or that libs configured by docker produce smaller images. I will check that, hopefully later today.

**Comment by cdaniel** [comment]
No luck today 

```
mongo_1  | 2017-06-29T17:46:24.632+0000 I JOURNAL  [initandlisten] preallocateIsFaster=true 7.18
web_1    | Error: EACCES: permission denied, scandir '/usr/app'
web_1    | TypeError: Cannot read property 'get' of undefined
web_1    |     at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:211:17)
web_1    |     at /usr/local/lib/node_modules/npm/bin/npm-cli.js:83:20
web_1    |     at cb (/usr/local/lib/node_modules/npm/lib/npm.js:215:22)
web_1    |     at /usr/local/lib/node_modules/npm/lib/npm.js:253:24
web_1    |     at /usr/local/lib/node_modules/npm/lib/config/core.js:81:7
web_1    |     at Array.forEach (native)
web_1    |     at /usr/local/lib/node_modules/npm/lib/config/core.js:80:13
web_1    |     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
web_1    |     at /usr/local/lib/node_modules/npm/lib/config/core.js:110:20
web_1    |     at /usr/local/lib/node_modules/npm/lib/config/load-prefix.js:48:7
web_1    | /usr/local/lib/node_modules/npm/lib/utils/error-handler.js:211
web_1    |   if (npm.config.get('json')) {
web_1    |                 ^
web_1    | 
web_1    | TypeError: Cannot read property 'get' of undefined
web_1    |     at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:211:17)
web_1    |     at emitOne (events.js:115:13)
web_1    |     at process.emit (events.js:210:7)
web_1    |     at process._fatalException (bootstrap_node.js:329:26)
mongo_1  | 2017-06-29T17:46:24.987+0000 I JOURNAL  [initandlisten] preallocateIsFaster=true 3.6
atlas2_web_1 exited with code 7
```

**Comment by bemosior** [comment]
Hi @cdaniel, it took a bit of troubleshooting before I could reproduce the error, but the cause is SELinux. I have committed a fix (applying a volume label) that should satisfy it.

[This post](https://stackoverflow.com/questions/44139279/docker-mounting-volume-with-permission-denied) helped, as did [this documentation](https://docs.docker.com/engine/tutorials/dockervolumes/).

**Comment by cdaniel** [comment]
Merged in, thanks!

**Comment by bemosior** [comment]
My pleasure!

**Pull request merged**
